import AnimatedText from "@/components/AnimatedText";
import Layout from "@/components/Layout";
import Head from "next/head";
import React, { useEffect, useRef } from "react";
import Image from "next/image";
import profilPic from "../../public/images/profile/3-Photo_Pro-zoomed.jpg";
import { useInView, useMotionValue, useSpring } from "framer-motion";

const AnimatedNumber = ({ value }) => {
  const ref = useRef(null);
  const motionValue = useMotionValue(0);
  const springValue = useSpring(motionValue, { duration: 3000 });
  const isInView = useInView(ref);

  useEffect(() => {
    if (isInView) {
      motionValue.set(value);
    }
  }, [isInView, motionValue, value]);

  useEffect(() => {
    springValue.on("change", (latest) => {
      if (ref.current && latest.toFixed(0) <= value) {
        ref.current.textContent = latest.toFixed(0);
      }
    });
  }, [springValue, value]);

  return <span ref={ref} className="inline-block text-7xl font-bold"></span>;
};

const about = () => {
  return (
    <>
      <Head>
        <title>EL KASMi hamza | About Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex w-full flex-col items-center justify-center">
        <Layout className="pt-10">
          <AnimatedText text="Code Creates Reality!" />
          <div className="grid w-full grid-cols-8 gap-16">
            <div className="col-span-3 flex-col items-start justify-start">
              <h2 className="mb4 text-lg font-bold uppercase text-dark/75">
                Biography
              </h2>
              <p className="font-medium my-4">
                Hi, I'm Hamza El Kasmi, a full-stack developer passionate about
                crafting powerful and user-friendly web applications. With
                expertise in Laravel, React.js, and UI/UX design, I bring ideas
                to life through clean and efficient code. 🚀
              </p>
              <p className="font-medium my-4">
                I believe development is more than just writing code - it's
                about solving problems and building seamless, engaging
                experiences for users.
              </p>
              <p className="font-medium my-4">
                Whether I'm building a web app, optimizing a backend, or
                designing a seamless user experience, I bring my commitment to
                clean code and user-focused solutions to every project. I look
                forward to contributing my skills and passion to your next
                venture.
              </p>
            </div>
            <div className="col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark bg-light p-8">
              <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark " />
              <Image
                src={profilPic}
                alt="hamza el kasmi"
                className="w-full h-auto rounded-2xl"
              />
            </div>
            <div className="col-span-2 flex-col items-end justify-between">
              <div className="flex flex-col items-end justify-center">
                <span className="inline-block text-7xl font-bold">
                  <AnimatedNumber value={10} />+
                </span>
                <h2 className="text-xl font-medium capitalize text-dark/75">
                  projects completed
                </h2>
              </div>
              <div className="flex flex-col items-end justify-center">
                <span className="inline-block text-7xl font-bold">
                  <AnimatedNumber value={1} />+
                </span>
                <h2 className="text-xl font-medium capitalize text-dark/75">
                  years of experience
                </h2>
              </div>
              <div className="flex flex-col items-end justify-center">
                <span className="inline-block text-7xl font-bold">
                  <AnimatedNumber value={10} />+
                </span>
                <h2 className="text-xl font-medium capitalize text-dark/75">
                  projects completed
                </h2>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
};

export default about;
