import Layout from "@/components/Layout";
import Image from "next/image";
import Head from "next/head";
import profilPic from "../../public/images/profile/ana-bg-rm.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen ">
        <Layout className="pt-0">
          <div className="w-full flex items-center justify-between">
            <div className="w-1/2">
              <Image
                src={profilPic}
                alt="hamza el kasmi"
                width={500}
                height={500}
                className="w-full h-auto"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Building Smart Solutions with Code and Creativity."
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium">
                Passionate Full-Stack Developer | Transforming Ideas into
                Powerful Web Applications Explore my latest projects and
                articles, highlighting my expertise in Laravel, React.js, and
                modern web development.
              </p>

              <div className="flex items-center self-start mt-4">
                <Link
                  href="/.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark mr-4"
                  download={true}
                >
                  Resume
                  <LinkArrow className="w-6 h-6 ml-2" />
                </Link>
                <Link
                  href="mailto:elkasmihamza05@gmail.com"
                  target={"_blank"}
                  className="text-lg font-medium capitalize text-dark underline"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
